### ISSUE TITLE
Plans to implement the forward KLD

### ISSUE THREAD

**Issue by odunkel** [ryushinn/flows-on-sphere#1]
Hey,

thanks for your implementation.
Have you considered reproducing the examples of Appendix J (Figure 11) which requires the forward KLD implementation?

I am looking forward to your answer.

Thanks and all the best

**Comment by ryushinn** [comment]
Hi odunkel,

Thanks for your comments. I am sorry that Appendix J is out of my needs about this paper so I won't try to implement. But you can feel free to modify or fork this repo to reproduce them in your own. Wish you luck! :)
